site_name: ReCoDE Exemplar
repo_url: https://github.com/ImperialCollegeLondon/ReCoDE-Data-Scarce-Behavioural-Anomaly-Detection

nav:
#   - 'Home': 'index.md'
    - 'Notebooks':
        - 'Dataset Preparation': '01_dataset_preparation.ipynb'
        - 'Preprocessing and Baseline': '02_preprocessing_and_baseline_iforest.ipynb'
        - 'Dimensionality and Clustering': '03_dimensionality_and_clustering.ipynb'
        - 'Model Interpretation': '04_model_interpretation_and_explanation.ipynb'
        - 'Ethics and Limitations': '05_ethics_and_limitations.ipynb'
        - 'Visual Polishing': '06_visual_polishing_and_citations.ipynb'
        - 'Reproducibility': '07_reproducibility_and_environment_testing.ipynb'
        - 'Finalised Summary': '08_finalised_summary_notebook.ipynb'

edit_uri: tree/main/docs/

theme:
  name: material
  logo: assets/iclogo.png
  favicon: assets/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - toc.follow
    - content.code.annotate

extra:
  homepage: https://imperialcollegelondon.github.io/ReCoDE-home/

plugins:
    - tags
    - search
    - include-markdown
    - mkdocs-jupyter
    - exclude:
        glob:
            - "LICENSE.md"

markdown_extensions:
    - meta
    - mdx_math:
        enable_dollar_delimiter: True
    - pymdownx.highlight:
        anchor_linenums: false
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
