name: Publish MkDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy MkDocs to gh-pages branch
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install documentation dependencies
        run: pip install mkdocs mkdocs-material mkdocs-jupyter mkdocs-include-markdown-plugin mkdocs-exclude pymdown-extensions
    # - name: Install dependencies (with mkdocs-jupyter)
    #    run: |
         # pip install -e .[dev]
         # pip install mkdocs
         # pip install mkdocs-material
         # pip install mkdocs-jupyter
         # pip install mkdocs-include-markdown-plugin
         # pip install mkdocs-exclude

      - name: Embed Markdown images in notebooks
        run: python utils/embed_images.py notebooks

      #  Removed the notebook copying step – mkdocs-jupyter handles this

      - name: Rewrite links in README.md for docs
        env:
          GH_URL: https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}
        run: |
          perl -i -pe '
            s#\]\(docs/([^):]+)\)#](docs/$1)#g; 
            s#\]\((?!https?:|mailto:|docs/)([^)]+)\)#]($ENV{GH_URL}/$1)#g
          ' README.md

      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force
